version: "3.1"

services:
  db:
    image: mysql
    hostname: irlpg_hostname
    container_name: irlpg_container_name
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./schema-mysql.sql:/docker-entrypoint-initdb.d/schema-mysql.sql